# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-22 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_zone_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default='fgvds', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='fsjkv', max_length=25),
            preserve_default=False,
        ),
    ]
