# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-23 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_zone_app', '0003_auto_20190922_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
